import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@@/styles/Home.module.css'
import { useEffect } from 'react'
import { appAPI } from '@@/api/api'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const testAPI = async (textData: string[], labels: string[]) => {
    await appAPI.train(textData, labels)
  }

  useEffect(() => {
    testAPI(["Указание метатегоов обязательна", "просто какой то текст для тестирования модели",
      "Указание метатегоов обязательна", "Указание метатегоов обязательна", "Указание метатегоов обязательна"],
      ["метатель", "Вот как то", "метатель", "метатель", "метатель"])
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

      </main>
    </>
  )
}
